"""
KOS Myelination Engine -- Compiles evolved ASTs into permanent Python engines.

When the Dream Mode Tree Swarm evolves a perfect AST for a task,
this module transpiles it into a standalone Python class and saves it
to kos/learned_engines/. The next Awake Mode benchmark auto-imports it.

This is the System-2 -> System-1 bridge:
    - System 2 (Dream Mode): hours of slow evolutionary search
    - Myelination: compile the evolved program into optimized Python
    - System 1 (Awake Mode): execute the compiled engine in milliseconds
"""

import os
import json
import time
import numpy as np
from typing import Optional, List, Tuple, Dict


LEARNED_DIR = os.path.join(os.path.dirname(__file__), "learned_engines")
MANIFEST_PATH = os.path.join(LEARNED_DIR, "manifest.json")


def myelinate(ast, task_id: str, train_pairs: List[Tuple[np.ndarray, np.ndarray]],
              description: str = "") -> Optional[str]:
    """
    Compile an evolved AST into a permanent Python engine file.

    Args:
        ast: The winning AST (nested tuple structure)
        task_id: The ARC task ID this was evolved for
        train_pairs: Training pairs for verification signature
        description: Human-readable description

    Returns:
        The module name of the saved engine, or None on failure.
    """
    # Deduplication: skip if this task already has a verified engine
    manifest = _load_manifest()
    for entry in manifest:
        if isinstance(entry, dict):
            existing_tid = entry.get("task_id", "")
            if existing_tid == task_id:
                print(f"[MYELINATE] Duplicate for {task_id} -- skipping (engine already exists)")
                return entry.get("module")

    # Generate unique module name
    timestamp = int(time.time())
    module_name = f"learned_{task_id}_{timestamp}"

    # Transpile AST to Python code
    python_code = _transpile_ast(ast, module_name, task_id, description)

    # Write the file
    filepath = os.path.join(LEARNED_DIR, f"{module_name}.py")
    with open(filepath, "w") as f:
        f.write(python_code)

    # Verify the generated code actually works
    try:
        exec(compile(python_code, filepath, "exec"))
    except Exception as e:
        print(f"[MYELINATE] Generated code has errors: {e}")
        os.remove(filepath)
        return None

    # Update manifest with new entry
    manifest.append({
        "module": module_name,
        "task_id": task_id,
        "task_ids": [task_id],
        "description": description or _ast_to_str(ast),
        "ast": _ast_to_serializable(ast),
        "timestamp": timestamp,
    })
    _save_manifest(manifest)

    print(f"[MYELINATE] Crystallized engine: {module_name}")
    print(f"[MYELINATE] AST: {_ast_to_str(ast)}")
    print(f"[MYELINATE] Saved to: {filepath}")

    return module_name


def _transpile_ast(ast, module_name: str, task_id: str, description: str) -> str:
    """Generate Python source code from an AST."""

    # Generate the apply function body
    apply_body = _transpile_node(ast, indent=1)

    code = f'''"""
Auto-generated learned engine: {module_name}
Task: {task_id}
Description: {description or _ast_to_str(ast)}
AST: {repr(ast)}

Generated by KOS Dream Mode myelination.
DO NOT EDIT -- this file is auto-generated.
"""

import numpy as np
from collections import Counter

try:
    from scipy.ndimage import label as scipy_label
except ImportError:
    scipy_label = None


def _resolve_color(token, grid):
    """Resolve a relational color token to an integer using the grid."""
    if isinstance(token, (int, float, np.integer)):
        return int(token)
    if not isinstance(token, str) or not token.startswith("COLOR_"):
        return token
    flat = grid.flatten()
    freq = Counter(int(v) for v in flat)
    nonzero = {{c: n for c, n in freq.items() if c != 0}}
    if not nonzero:
        return 0
    if token == "COLOR_MAX":
        return max(nonzero, key=nonzero.get)
    elif token == "COLOR_MIN":
        return min(nonzero, key=nonzero.get)
    elif token == "COLOR_BG":
        return max(freq, key=freq.get) if freq else 0
    elif token == "COLOR_SECOND":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[1] if len(mc) >= 2 else mc[0] if mc else 0
    elif token == "COLOR_UNIQUE":
        uniques = [c for c, n in nonzero.items() if n == 1]
        return uniques[0] if uniques else min(nonzero, key=nonzero.get)
    elif token == "COLOR_FG_1":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[0] if mc else 0
    elif token == "COLOR_FG_2":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[1] if len(mc) >= 2 else mc[0] if mc else 0
    return 0


def detect_rule(train_pairs):
    """Check if this learned engine applies to the given training pairs."""
    for inp, out in train_pairs:
        pred = apply_rule(inp, {{}})
        if pred.shape != out.shape or not np.array_equal(pred, out):
            return None
    return {{
        "type": "learned_{task_id}",
        "description": "{description or _ast_to_str(ast)}",
        "target_color": None,
        "displacement": (0, 0),
        "color_swap": None,
        "worst_error": 0.0,
    }}


def apply_rule(grid, rule=None):
    """Apply the learned transformation."""
    _orig_grid = grid.copy()
    state = grid.copy()
{apply_body}
    return state


def _gravity(grid, direction):
    """Drop non-zero pixels in a direction."""
    result = np.zeros_like(grid)
    h, w = grid.shape
    if direction == "down":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[h - len(col) + i, c] = v
    elif direction == "up":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[i, c] = v
    elif direction == "right":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, w - len(row) + i] = v
    elif direction == "left":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, i] = v
    return result


def _for_each_object(grid, transform_fn):
    """Apply transform to each connected component."""
    if scipy_label is None:
        return grid
    mask = grid > 0
    if not np.any(mask):
        return grid
    labeled, n = scipy_label(mask)
    if n == 0 or n > 30:
        return grid
    out = np.zeros_like(grid)
    for i in range(1, n + 1):
        obj_mask = (labeled == i)
        isolated = np.where(obj_mask, grid, 0)
        processed = transform_fn(isolated)
        if processed.shape == out.shape:
            pm = processed != 0
            out[pm] = processed[pm]
    return out
'''
    return code


def _emit_val(val):
    """Emit a value for transpiled code — resolve relational tokens."""
    if isinstance(val, str) and (val.startswith("COLOR_") or val.startswith("ORIG_COLOR_")):
        if val.startswith("ORIG_"):
            return f'_resolve_color("{val[5:]}", _orig_grid)'
        return f'_resolve_color("{val}", _orig_grid)'
    # Phase 2 literal colors: LIT_0 through LIT_9
    if isinstance(val, str) and val.startswith("LIT_"):
        return val[4:]  # LIT_8 -> "8"
    return repr(val)


def _transpile_node(ast, indent: int = 1) -> str:
    """Recursively transpile an AST node into Python code lines."""
    prefix = "    " * indent

    # String leaf: atomic operation
    if isinstance(ast, str):
        return _transpile_leaf(ast, indent)

    # Single-element tuple: treat as leaf
    if isinstance(ast, tuple) and len(ast) == 1 and isinstance(ast[0], str):
        return _transpile_leaf(ast[0], indent)

    # Tuple node
    if isinstance(ast, tuple) and len(ast) >= 2 and isinstance(ast[0], str):
        op = ast[0]

        if op == "SWAP" and len(ast) == 3:
            c1, c2 = _emit_val(ast[1]), _emit_val(ast[2])
            return (f"{prefix}_c1, _c2 = {c1}, {c2}\n"
                    f"{prefix}m1, m2 = state == _c1, state == _c2\n"
                    f"{prefix}state[m1] = _c2\n"
                    f"{prefix}state[m2] = _c1\n")

        elif op == "SWAP" and len(ast) == 4:
            # Phase 2 format: ('SWAP', grid_ast, color1, color2)
            grid_code = _transpile_node(ast[1], indent)
            c1, c2 = _emit_val(ast[2]), _emit_val(ast[3])
            return (grid_code +
                    f"{prefix}_c1, _c2 = {c1}, {c2}\n"
                    f"{prefix}m1, m2 = state == _c1, state == _c2\n"
                    f"{prefix}state[m1] = _c2\n"
                    f"{prefix}state[m2] = _c1\n")

        elif op == "RECOLOR" and len(ast) == 3:
            src, dst = _emit_val(ast[1]), _emit_val(ast[2])
            return f"{prefix}state[state == {src}] = {dst}\n"

        elif op == "RECOLOR" and len(ast) == 4:
            # Phase 2 format: ('RECOLOR', grid_ast, from_color, to_color)
            grid_code = _transpile_node(ast[1], indent)
            src, dst = _emit_val(ast[2]), _emit_val(ast[3])
            return grid_code + f"{prefix}state[state == {src}] = {dst}\n"

        elif op == "MASK" and len(ast) == 2:
            v = _emit_val(ast[1])
            return f"{prefix}state = np.where(state == {v}, {v}, 0)\n"

        elif op == "FILL_BG" and len(ast) == 2:
            v = _emit_val(ast[1])
            return f"{prefix}state[state == 0] = {v}\n"

        elif op == "RECOLOR_ALL_TO_MAX":
            return (f"{prefix}_cmax = _resolve_color('COLOR_MAX', _orig_grid)\n"
                    f"{prefix}state[state != 0] = _cmax\n")

        elif op == "IF_COLOR" and len(ast) == 4:
            v = _emit_val(ast[1])
            true_body = _transpile_node(ast[2], indent + 1)
            false_body = _transpile_node(ast[3], indent + 1)
            return (f"{prefix}if {v} in state:\n"
                    f"{true_body}"
                    f"{prefix}else:\n"
                    f"{false_body}")

        elif op == "OVERLAY" and len(ast) == 3:
            return (f"{prefix}state_a = state.copy()\n"
                    f"{_transpile_node(ast[1], indent)}"
                    f"{prefix}result_a = state.copy()\n"
                    f"{prefix}state = state_a.copy()\n"
                    f"{_transpile_node(ast[2], indent)}"
                    f"{prefix}result_b = state.copy()\n"
                    f"{prefix}state = result_a.copy()\n"
                    f"{prefix}mask = result_b != 0\n"
                    f"{prefix}state[mask] = result_b[mask]\n")

        elif op == "FOR_EACH_OBJECT" and len(ast) == 2:
            sub_body = _transpile_node(ast[1], indent=2)
            return (f"{prefix}def _sub_transform(state):\n"
                    f"{prefix}    _orig_grid = state.copy()\n"
                    f"{sub_body}"
                    f"{prefix}    return state\n"
                    f"{prefix}state = _for_each_object(state, _sub_transform)\n")

        elif op == "SEQ":
            lines = ""
            for sub in ast[1:]:
                lines += _transpile_node(sub, indent)
            return lines

        elif op == "CROP_TO_COLOR" and len(ast) == 2:
            v = _emit_val(ast[1])
            return (f"{prefix}_cv = {v}\n"
                    f"{prefix}nz = np.argwhere(state == _cv)\n"
                    f"{prefix}if len(nz) > 0:\n"
                    f"{prefix}    r0, c0 = nz.min(axis=0)\n"
                    f"{prefix}    r1, c1 = nz.max(axis=0)\n"
                    f"{prefix}    state = state[r0:r1+1, c0:c1+1].copy()\n")

        elif op == "CROP_TO_COLOR" and len(ast) == 3:
            # Phase 2 format: ('CROP_TO_COLOR', grid_ast, color)
            grid_code = _transpile_node(ast[1], indent)
            v = _emit_val(ast[2])
            return (grid_code +
                    f"{prefix}_cv = {v}\n"
                    f"{prefix}nz = np.argwhere(state == _cv)\n"
                    f"{prefix}if len(nz) > 0:\n"
                    f"{prefix}    r0, c0 = nz.min(axis=0)\n"
                    f"{prefix}    r1, c1 = nz.max(axis=0)\n"
                    f"{prefix}    state = state[r0:r1+1, c0:c1+1].copy()\n")

        elif op == "MASK_FILL" and len(ast) == 4:
            # Phase 2: ('MASK_FILL', grid_ast, mask_ast, color)
            grid_code = _transpile_node(ast[1], indent)
            # Execute mask as separate state computation
            v = _emit_val(ast[3])
            return (grid_code +
                    f"{prefix}_saved = state.copy()\n"
                    f"{_transpile_node(ast[2], indent)}"
                    f"{prefix}_mask = (state != 0).astype(bool)\n"
                    f"{prefix}state = _saved\n"
                    f"{prefix}state[_mask] = {v}\n")

        elif op == "MASK_SELECT" and len(ast) == 3:
            # Phase 2: ('MASK_SELECT', grid_ast, mask_ast)
            grid_code = _transpile_node(ast[1], indent)
            return (grid_code +
                    f"{prefix}_saved = state.copy()\n"
                    f"{_transpile_node(ast[2], indent)}"
                    f"{prefix}_mask = (state != 0).astype(bool)\n"
                    f"{prefix}state = np.zeros_like(_saved)\n"
                    f"{prefix}state[_mask] = _saved[_mask]\n")

        elif op == "NONZERO_MASK":
            child_code = _transpile_node(ast[1], indent) if len(ast) > 1 else ""
            return child_code + f"{prefix}state = (state != 0).astype(state.dtype)\n"

        elif op == "MASK_NOT":
            child_code = _transpile_node(ast[1], indent) if len(ast) > 1 else ""
            return child_code + f"{prefix}state = (1 - (state != 0).astype(state.dtype))\n"

        elif op == "FILL_BG" and len(ast) == 3:
            # Phase 2 format: ('FILL_BG', grid_ast, color)
            grid_code = _transpile_node(ast[1], indent)
            v = _emit_val(ast[2])
            return grid_code + f"{prefix}state[state == 0] = {v}\n"

        elif op == "RECOLOR_ALL_TO_MAX":
            return (f"{prefix}_cmax = _resolve_color('COLOR_MAX', _orig_grid)\n"
                    f"{prefix}state[state != 0] = _cmax\n")

        # Generic unary op wrapping a sub-AST: op(child)
        # e.g., ('MIRROR_V', ('MIRROR_H', 'INPUT')) or ('CROP_NONZERO', ('FLIP_H', 'INPUT'))
        if len(ast) == 2:
            child = ast[1]
            # First execute the child (transforms state)
            child_code = _transpile_node(child, indent)
            # Then apply the leaf op on the result
            leaf_code = _transpile_leaf(op, indent)
            return child_code + leaf_code

        # Generic binary op wrapping sub-ASTs: op(child1, child2)
        # For RECOLOR/SWAP with sub-AST as grid arg
        if len(ast) == 3 and op in ("RECOLOR", "SWAP"):
            grid_child = ast[1] if not isinstance(ast[1], str) else None
            if grid_child is not None:
                # Execute grid sub-tree first, then apply recolor
                child_code = _transpile_node(grid_child, indent)
                c1, c2 = _emit_val(ast[1] if isinstance(ast[1], str) else "dummy"), _emit_val(ast[2])
                if op == "SWAP":
                    return (child_code +
                            f"{prefix}_c1, _c2 = {_emit_val(ast[1])}, {_emit_val(ast[2])}\n"
                            f"{prefix}m1, m2 = state == _c1, state == _c2\n"
                            f"{prefix}state[m1] = _c2\n"
                            f"{prefix}state[m2] = _c1\n")
                else:
                    return (child_code +
                            f"{prefix}state[state == {_emit_val(ast[1])}] = {_emit_val(ast[2])}\n")

    # Fallback
    return f"{prefix}pass  # Unknown AST node: {repr(ast)}\n"


def _transpile_leaf(op: str, indent: int) -> str:
    """Transpile a string atomic operation."""
    prefix = "    " * indent
    leaf_map = {
        "ROT90": "state = np.rot90(state, k=-1)",
        "ROT180": "state = np.rot90(state, k=2)",
        "ROT270": "state = np.rot90(state, k=1)",
        "FLIP_H": "state = np.fliplr(state)",
        "FLIP_V": "state = np.flipud(state)",
        "TRANSPOSE": "state = state.T.copy()",
        "GRAVITY_DOWN": "state = _gravity(state, 'down')",
        "GRAVITY_UP": "state = _gravity(state, 'up')",
        "GRAVITY_LEFT": "state = _gravity(state, 'left')",
        "GRAVITY_RIGHT": "state = _gravity(state, 'right')",
        "IDENTITY": "pass",
        "INPUT": "pass  # state is already the input grid",
        "ORIG_INPUT": "state = _orig_grid.copy()",
        "CROP_NONZERO": ("nz = np.argwhere(state != 0)\n"
                         f"{prefix}if len(nz) > 0:\n"
                         f"{prefix}    r0, c0 = nz.min(axis=0)\n"
                         f"{prefix}    r1, c1 = nz.max(axis=0)\n"
                         f"{prefix}    state = state[r0:r1+1, c0:c1+1].copy()"),
        "SHIFT_UP": "state = np.roll(state, -1, axis=0); state[-1, :] = 0",
        "SHIFT_DOWN": "state = np.roll(state, 1, axis=0); state[0, :] = 0",
        "SHIFT_LEFT": "state = np.roll(state, -1, axis=1); state[:, -1] = 0",
        "SHIFT_RIGHT": "state = np.roll(state, 1, axis=1); state[:, 0] = 0",
        "SORT_ROWS": "state = np.sort(state, axis=1)",
        "SORT_COLS": "state = np.sort(state, axis=0)",
        "RECOLOR_ALL_TO_MAX": (
            "_cmax = _resolve_color('COLOR_MAX', _orig_grid)\n"
            f"{prefix}state[state != 0] = _cmax"
        ),
        "DELETE_ROWS_ZERO": (
            "mask = np.any(state != 0, axis=1)\n"
            f"{prefix}if mask.any(): state = state[mask]"
        ),
        "DELETE_COLS_ZERO": (
            "mask = np.any(state != 0, axis=0)\n"
            f"{prefix}if mask.any(): state = state[:, mask]"
        ),
        "UPSCALE_2X": "state = np.repeat(np.repeat(state, 2, axis=0), 2, axis=1)",
        "DOWNSCALE_2X": (
            "h, w = state.shape\n"
            f"{prefix}if h >= 2 and w >= 2: state = state[::2, ::2].copy()"
        ),
        "EXTRACT_QUADRANT_TL": (
            "h, w = state.shape\n"
            f"{prefix}state = state[:h//2, :w//2].copy()"
        ),
        "EXTRACT_QUADRANT_TR": (
            "h, w = state.shape\n"
            f"{prefix}state = state[:h//2, w//2:].copy()"
        ),
        "EXTRACT_QUADRANT_BL": (
            "h, w = state.shape\n"
            f"{prefix}state = state[h//2:, :w//2].copy()"
        ),
        "EXTRACT_QUADRANT_BR": (
            "h, w = state.shape\n"
            f"{prefix}state = state[h//2:, w//2:].copy()"
        ),
        "UPSCALE_3X": "state = np.repeat(np.repeat(state, 3, axis=0), 3, axis=1)",
        "TESSELLATE_2X2": "state = np.tile(state, (2, 2))",
        "TESSELLATE_1X3": "state = np.tile(state, (1, 3))",
        "TESSELLATE_3X1": "state = np.tile(state, (3, 1))",
        "PAD_ZERO_1": "state = np.pad(state, 1, mode='constant', constant_values=0)",
        "CROP_TO_NONBG": (
            "_bg = _resolve_color('COLOR_BG', _orig_grid)\n"
            f"{prefix}nz = np.argwhere(state != _bg)\n"
            f"{prefix}if len(nz) > 0:\n"
            f"{prefix}    r0, c0 = nz.min(axis=0)\n"
            f"{prefix}    r1, c1 = nz.max(axis=0)\n"
            f"{prefix}    state = state[r0:r1+1, c0:c1+1].copy()"
        ),
        "KEEP_MOST_FREQUENT": (
            "_freq = {}\n"
            f"{prefix}for v in state.flat:\n"
            f"{prefix}    if int(v) != 0: _freq[int(v)] = _freq.get(int(v), 0) + 1\n"
            f"{prefix}if _freq:\n"
            f"{prefix}    _keep = max(_freq, key=_freq.get)\n"
            f"{prefix}    state = np.where((state == _keep) | (state == 0), state, 0)"
        ),
        "RECOLOR_NONMAX_TO_BG": (
            "_cmax = _resolve_color('COLOR_MAX', _orig_grid)\n"
            f"{prefix}state = np.where((state == _cmax) | (state == 0), state, 0)"
        ),
        "MASK": (
            "pass  # MASK as leaf is a no-op (needs color arg)"
        ),
        "FILL_BG": (
            "pass  # FILL_BG as leaf is a no-op (needs color arg)"
        ),
        "CROP_TO_COLOR": (
            "pass  # CROP_TO_COLOR as leaf is a no-op (needs color arg)"
        ),
        # Phase 2 new ops
        "TILE_1X2": "state = np.tile(state, (1, 2))",
        "TILE_2X1": "state = np.tile(state, (2, 1))",
        "TILE_1X3": "state = np.tile(state, (1, 3))",
        "TILE_3X1": "state = np.tile(state, (3, 1))",
        "TILE_2X2": "state = np.tile(state, (2, 2))",
        "TILE_3X3": "state = np.tile(state, (3, 3))",
        "MIRROR_H": "state = np.concatenate([state, np.fliplr(state)], axis=1)",
        "MIRROR_V": "state = np.concatenate([state, np.flipud(state)], axis=0)",
        "REVERSE_ROWS": "state = state[::-1, :].copy()",
        "REVERSE_COLS": "state = state[:, ::-1].copy()",
        "DEDUP_ROWS": (
            "_, idx = np.unique([tuple(r) for r in state], return_index=True, axis=0)\n"
            f"{prefix}state = state[np.sort(idx)]"
        ),
        "DEDUP_COLS": (
            "_, idx = np.unique([tuple(c) for c in state.T], return_index=True, axis=0)\n"
            f"{prefix}state = state[:, np.sort(idx)]"
        ),
        "HOLLOW_RECT": (
            "if state.shape[0] > 2 and state.shape[1] > 2:\n"
            f"{prefix}    state = state.copy(); state[1:-1, 1:-1] = 0"
        ),
        "DOWNSCALE_3X": (
            "h, w = state.shape\n"
            f"{prefix}if h >= 3 and w >= 3:\n"
            f"{prefix}    nh, nw = h // 3, w // 3\n"
            f"{prefix}    result = np.zeros((nh, nw), dtype=state.dtype)\n"
            f"{prefix}    for i in range(nh):\n"
            f"{prefix}        for j in range(nw):\n"
            f"{prefix}            block = state[i*3:(i+1)*3, j*3:(j+1)*3].ravel()\n"
            f"{prefix}            result[i, j] = Counter(int(v) for v in block).most_common(1)[0][0]\n"
            f"{prefix}    state = result"
        ),
    }

    code = leaf_map.get(op, f"pass  # Unknown op: {op}")
    return f"{prefix}{code}\n"


def _ast_to_str(ast) -> str:
    """Pretty-print an AST."""
    if isinstance(ast, str):
        return ast
    if isinstance(ast, tuple) and len(ast) >= 2:
        op = ast[0]
        if isinstance(op, str):
            if op in ("SWAP", "RECOLOR", "MASK", "FILL_BG"):
                return f"{op}({','.join(str(x) for x in ast[1:])})"
            elif op == "IF_COLOR":
                return f"IF({ast[1]}, {_ast_to_str(ast[2])}, {_ast_to_str(ast[3])})"
            elif op == "OVERLAY":
                return f"OVERLAY({_ast_to_str(ast[1])}, {_ast_to_str(ast[2])})"
            elif op == "FOR_EACH_OBJECT":
                return f"FOR_EACH({_ast_to_str(ast[1])})"
            elif op == "SEQ":
                return " -> ".join(_ast_to_str(s) for s in ast[1:])
    return repr(ast)


def _ast_to_serializable(ast):
    """Convert AST to JSON-serializable form."""
    if isinstance(ast, str):
        return ast
    if isinstance(ast, (tuple, list)):
        return [_ast_to_serializable(x) for x in ast]
    if isinstance(ast, (int, float)):
        return ast
    if isinstance(ast, np.integer):
        return int(ast)
    return str(ast)


def _load_manifest():
    if not os.path.exists(MANIFEST_PATH):
        return []
    with open(MANIFEST_PATH) as f:
        return json.load(f)


def _save_manifest(manifest):
    with open(MANIFEST_PATH, "w") as f:
        json.dump(manifest, f, indent=2)
