"""
KOS Myelination Engine -- Compiles evolved ASTs into permanent Python engines.

When the Dream Mode Tree Swarm evolves a perfect AST for a task,
this module transpiles it into a standalone Python class and saves it
to kos/learned_engines/. The next Awake Mode benchmark auto-imports it.

This is the System-2 -> System-1 bridge:
    - System 2 (Dream Mode): hours of slow evolutionary search
    - Myelination: compile the evolved program into optimized Python
    - System 1 (Awake Mode): execute the compiled engine in milliseconds
"""

import os
import json
import time
import numpy as np
from typing import Optional, List, Tuple, Dict


LEARNED_DIR = os.path.join(os.path.dirname(__file__), "learned_engines")
MANIFEST_PATH = os.path.join(LEARNED_DIR, "manifest.json")


def myelinate(ast, task_id: str, train_pairs: List[Tuple[np.ndarray, np.ndarray]],
              description: str = "") -> Optional[str]:
    """
    Compile an evolved AST into a permanent Python engine file.

    Args:
        ast: The winning AST (nested tuple structure)
        task_id: The ARC task ID this was evolved for
        train_pairs: Training pairs for verification signature
        description: Human-readable description

    Returns:
        The module name of the saved engine, or None on failure.
    """
    # Generate unique module name
    timestamp = int(time.time())
    module_name = f"learned_{task_id}_{timestamp}"

    # Transpile AST to Python code
    python_code = _transpile_ast(ast, module_name, task_id, description)

    # Write the file
    filepath = os.path.join(LEARNED_DIR, f"{module_name}.py")
    with open(filepath, "w") as f:
        f.write(python_code)

    # Verify the generated code actually works
    try:
        exec(compile(python_code, filepath, "exec"))
    except Exception as e:
        print(f"[MYELINATE] Generated code has errors: {e}")
        os.remove(filepath)
        return None

    # Update manifest
    manifest = _load_manifest()
    manifest.append({
        "module": module_name,
        "task_id": task_id,
        "task_ids": [task_id],
        "description": description or _ast_to_str(ast),
        "ast": _ast_to_serializable(ast),
        "timestamp": timestamp,
    })
    _save_manifest(manifest)

    print(f"[MYELINATE] Crystallized engine: {module_name}")
    print(f"[MYELINATE] AST: {_ast_to_str(ast)}")
    print(f"[MYELINATE] Saved to: {filepath}")

    return module_name


def _transpile_ast(ast, module_name: str, task_id: str, description: str) -> str:
    """Generate Python source code from an AST."""

    # Generate the apply function body
    apply_body = _transpile_node(ast, indent=1)

    code = f'''"""
Auto-generated learned engine: {module_name}
Task: {task_id}
Description: {description or _ast_to_str(ast)}
AST: {repr(ast)}

Generated by KOS Dream Mode myelination.
DO NOT EDIT -- this file is auto-generated.
"""

import numpy as np

try:
    from scipy.ndimage import label as scipy_label
except ImportError:
    scipy_label = None


def detect_rule(train_pairs):
    """Check if this learned engine applies to the given training pairs."""
    for inp, out in train_pairs:
        pred = apply_rule(inp, {{}})
        if pred.shape != out.shape or not np.array_equal(pred, out):
            return None
    return {{
        "type": "learned_{task_id}",
        "description": "{description or _ast_to_str(ast)}",
        "target_color": None,
        "displacement": (0, 0),
        "color_swap": None,
        "worst_error": 0.0,
    }}


def apply_rule(grid, rule=None):
    """Apply the learned transformation."""
    state = grid.copy()
{apply_body}
    return state


def _gravity(grid, direction):
    """Drop non-zero pixels in a direction."""
    result = np.zeros_like(grid)
    h, w = grid.shape
    if direction == "down":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[h - len(col) + i, c] = v
    elif direction == "up":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[i, c] = v
    elif direction == "right":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, w - len(row) + i] = v
    elif direction == "left":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, i] = v
    return result


def _for_each_object(grid, transform_fn):
    """Apply transform to each connected component."""
    if scipy_label is None:
        return grid
    mask = grid > 0
    if not np.any(mask):
        return grid
    labeled, n = scipy_label(mask)
    if n == 0 or n > 30:
        return grid
    out = np.zeros_like(grid)
    for i in range(1, n + 1):
        obj_mask = (labeled == i)
        isolated = np.where(obj_mask, grid, 0)
        processed = transform_fn(isolated)
        if processed.shape == out.shape:
            pm = processed != 0
            out[pm] = processed[pm]
    return out
'''
    return code


def _transpile_node(ast, indent: int = 1) -> str:
    """Recursively transpile an AST node into Python code lines."""
    prefix = "    " * indent

    # String leaf: atomic operation
    if isinstance(ast, str):
        return _transpile_leaf(ast, indent)

    # Tuple node
    if isinstance(ast, tuple) and len(ast) >= 2 and isinstance(ast[0], str):
        op = ast[0]

        if op == "SWAP" and len(ast) == 3:
            c1, c2 = ast[1], ast[2]
            return (f"{prefix}m1, m2 = state == {c1}, state == {c2}\n"
                    f"{prefix}state[m1] = {c2}\n"
                    f"{prefix}state[m2] = {c1}\n")

        elif op == "RECOLOR" and len(ast) == 3:
            return f"{prefix}state[state == {ast[1]}] = {ast[2]}\n"

        elif op == "MASK" and len(ast) == 2:
            return f"{prefix}state = np.where(state == {ast[1]}, {ast[1]}, 0)\n"

        elif op == "FILL_BG" and len(ast) == 2:
            return f"{prefix}state[state == 0] = {ast[1]}\n"

        elif op == "IF_COLOR" and len(ast) == 4:
            true_body = _transpile_node(ast[2], indent + 1)
            false_body = _transpile_node(ast[3], indent + 1)
            return (f"{prefix}if {ast[1]} in state:\n"
                    f"{true_body}"
                    f"{prefix}else:\n"
                    f"{false_body}")

        elif op == "OVERLAY" and len(ast) == 3:
            return (f"{prefix}state_a = state.copy()\n"
                    f"{_transpile_node(ast[1], indent)}"
                    f"{prefix}result_a = state.copy()\n"
                    f"{prefix}state = state_a.copy()\n"
                    f"{_transpile_node(ast[2], indent)}"
                    f"{prefix}result_b = state.copy()\n"
                    f"{prefix}state = result_a.copy()\n"
                    f"{prefix}mask = result_b != 0\n"
                    f"{prefix}state[mask] = result_b[mask]\n")

        elif op == "FOR_EACH_OBJECT" and len(ast) == 2:
            # Generate a lambda for the sub-transform
            sub_body = _transpile_node(ast[1], indent=2)
            return (f"{prefix}def _sub_transform(state):\n"
                    f"{sub_body}"
                    f"{prefix}    return state\n"
                    f"{prefix}state = _for_each_object(state, _sub_transform)\n")

        elif op == "SEQ":
            lines = ""
            for sub in ast[1:]:
                lines += _transpile_node(sub, indent)
            return lines

    # Fallback
    return f"{prefix}pass  # Unknown AST node: {repr(ast)}\n"


def _transpile_leaf(op: str, indent: int) -> str:
    """Transpile a string atomic operation."""
    prefix = "    " * indent
    leaf_map = {
        "ROT90": "state = np.rot90(state, k=-1)",
        "ROT180": "state = np.rot90(state, k=2)",
        "ROT270": "state = np.rot90(state, k=1)",
        "FLIP_H": "state = np.fliplr(state)",
        "FLIP_V": "state = np.flipud(state)",
        "TRANSPOSE": "state = state.T.copy()",
        "GRAVITY_DOWN": "state = _gravity(state, 'down')",
        "GRAVITY_UP": "state = _gravity(state, 'up')",
        "GRAVITY_LEFT": "state = _gravity(state, 'left')",
        "GRAVITY_RIGHT": "state = _gravity(state, 'right')",
        "IDENTITY": "pass",
        "CROP_NONZERO": ("nz = np.argwhere(state != 0)\n"
                         f"{prefix}if len(nz) > 0:\n"
                         f"{prefix}    r0, c0 = nz.min(axis=0)\n"
                         f"{prefix}    r1, c1 = nz.max(axis=0)\n"
                         f"{prefix}    state = state[r0:r1+1, c0:c1+1].copy()"),
        "SHIFT_UP": "state = np.roll(state, -1, axis=0); state[-1, :] = 0",
        "SHIFT_DOWN": "state = np.roll(state, 1, axis=0); state[0, :] = 0",
        "SHIFT_LEFT": "state = np.roll(state, -1, axis=1); state[:, -1] = 0",
        "SHIFT_RIGHT": "state = np.roll(state, 1, axis=1); state[:, 0] = 0",
        "SORT_ROWS": "state = np.sort(state, axis=1)",
        "SORT_COLS": "state = np.sort(state, axis=0)",
    }

    code = leaf_map.get(op, f"pass  # Unknown op: {op}")
    return f"{prefix}{code}\n"


def _ast_to_str(ast) -> str:
    """Pretty-print an AST."""
    if isinstance(ast, str):
        return ast
    if isinstance(ast, tuple) and len(ast) >= 2:
        op = ast[0]
        if isinstance(op, str):
            if op in ("SWAP", "RECOLOR", "MASK", "FILL_BG"):
                return f"{op}({','.join(str(x) for x in ast[1:])})"
            elif op == "IF_COLOR":
                return f"IF({ast[1]}, {_ast_to_str(ast[2])}, {_ast_to_str(ast[3])})"
            elif op == "OVERLAY":
                return f"OVERLAY({_ast_to_str(ast[1])}, {_ast_to_str(ast[2])})"
            elif op == "FOR_EACH_OBJECT":
                return f"FOR_EACH({_ast_to_str(ast[1])})"
            elif op == "SEQ":
                return " -> ".join(_ast_to_str(s) for s in ast[1:])
    return repr(ast)


def _ast_to_serializable(ast):
    """Convert AST to JSON-serializable form."""
    if isinstance(ast, str):
        return ast
    if isinstance(ast, (tuple, list)):
        return [_ast_to_serializable(x) for x in ast]
    if isinstance(ast, (int, float)):
        return ast
    if isinstance(ast, np.integer):
        return int(ast)
    return str(ast)


def _load_manifest():
    if not os.path.exists(MANIFEST_PATH):
        return []
    with open(MANIFEST_PATH) as f:
        return json.load(f)


def _save_manifest(manifest):
    with open(MANIFEST_PATH, "w") as f:
        json.dump(manifest, f, indent=2)
