"""
Auto-generated learned engine: learned_6f8cd79b_1775268933
Task: 6f8cd79b
Description: Evolved for 6f8cd79b: SEQ(SEQ(SWAP(8,0) -> ROT90 -> SHIFT_LEFT -> SHIFT_DOWN) -> FOR_EACH(SWAP(0,8)) -> OVERLAY(ROT90, ROT270))
AST: ('SEQ', ('SEQ', ('SWAP', 8, 0), 'ROT90', 'SHIFT_LEFT', 'SHIFT_DOWN'), ('FOR_EACH_OBJECT', ('SWAP', 0, 8)), ('OVERLAY', 'ROT90', 'ROT270'))

Generated by KOS Dream Mode myelination.
DO NOT EDIT -- this file is auto-generated.
"""

import numpy as np

try:
    from scipy.ndimage import label as scipy_label
except ImportError:
    scipy_label = None


def detect_rule(train_pairs):
    """Check if this learned engine applies to the given training pairs."""
    for inp, out in train_pairs:
        pred = apply_rule(inp, {})
        if pred.shape != out.shape or not np.array_equal(pred, out):
            return None
    return {
        "type": "learned_6f8cd79b",
        "description": "Evolved for 6f8cd79b: SEQ(SEQ(SWAP(8,0) -> ROT90 -> SHIFT_LEFT -> SHIFT_DOWN) -> FOR_EACH(SWAP(0,8)) -> OVERLAY(ROT90, ROT270))",
        "target_color": None,
        "displacement": (0, 0),
        "color_swap": None,
        "worst_error": 0.0,
    }


def apply_rule(grid, rule=None):
    """Apply the learned transformation."""
    state = grid.copy()
    m1, m2 = state == 8, state == 0
    state[m1] = 0
    state[m2] = 8
    state = np.rot90(state, k=-1)
    state = np.roll(state, -1, axis=1); state[:, -1] = 0
    state = np.roll(state, 1, axis=0); state[0, :] = 0
    def _sub_transform(state):
        m1, m2 = state == 0, state == 8
        state[m1] = 8
        state[m2] = 0
        return state
    state = _for_each_object(state, _sub_transform)
    state_a = state.copy()
    state = np.rot90(state, k=-1)
    result_a = state.copy()
    state = state_a.copy()
    state = np.rot90(state, k=1)
    result_b = state.copy()
    state = result_a.copy()
    mask = result_b != 0
    state[mask] = result_b[mask]

    return state


def _gravity(grid, direction):
    """Drop non-zero pixels in a direction."""
    result = np.zeros_like(grid)
    h, w = grid.shape
    if direction == "down":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[h - len(col) + i, c] = v
    elif direction == "up":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[i, c] = v
    elif direction == "right":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, w - len(row) + i] = v
    elif direction == "left":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, i] = v
    return result


def _for_each_object(grid, transform_fn):
    """Apply transform to each connected component."""
    if scipy_label is None:
        return grid
    mask = grid > 0
    if not np.any(mask):
        return grid
    labeled, n = scipy_label(mask)
    if n == 0 or n > 30:
        return grid
    out = np.zeros_like(grid)
    for i in range(1, n + 1):
        obj_mask = (labeled == i)
        isolated = np.where(obj_mask, grid, 0)
        processed = transform_fn(isolated)
        if processed.shape == out.shape:
            pm = processed != 0
            out[pm] = processed[pm]
    return out
