"""
Auto-generated learned engine: learned_5582e5ca_1775397566
Task: 5582e5ca
Description: Evolved for 5582e5ca: SEQ(FOR_EACH(FOR_EACH(('CROP_TO_COLOR', 'COLOR_UNIQUE'))) -> SEQ(MASK(COLOR_FG_1) -> RECOLOR(COLOR_SECOND,ORIG_COLOR_BG) -> SWAP(COLOR_MAX,COLOR_FG_2)) -> SWAP(COLOR_SECOND,COLOR_FG_2))
AST: ('SEQ', ('FOR_EACH_OBJECT', ('FOR_EACH_OBJECT', ('CROP_TO_COLOR', 'COLOR_UNIQUE'))), ('SEQ', ('MASK', 'COLOR_FG_1'), ('RECOLOR', 'COLOR_SECOND', 'ORIG_COLOR_BG'), ('SWAP', 'COLOR_MAX', 'COLOR_FG_2')), ('SWAP', 'COLOR_SECOND', 'COLOR_FG_2'))

Generated by KOS Dream Mode myelination.
DO NOT EDIT -- this file is auto-generated.
"""

import numpy as np
from collections import Counter

try:
    from scipy.ndimage import label as scipy_label
except ImportError:
    scipy_label = None


def _resolve_color(token, grid):
    """Resolve a relational color token to an integer using the grid."""
    if isinstance(token, (int, float, np.integer)):
        return int(token)
    if not isinstance(token, str) or not token.startswith("COLOR_"):
        return token
    flat = grid.flatten()
    freq = Counter(int(v) for v in flat)
    nonzero = {c: n for c, n in freq.items() if c != 0}
    if not nonzero:
        return 0
    if token == "COLOR_MAX":
        return max(nonzero, key=nonzero.get)
    elif token == "COLOR_MIN":
        return min(nonzero, key=nonzero.get)
    elif token == "COLOR_BG":
        return max(freq, key=freq.get) if freq else 0
    elif token == "COLOR_SECOND":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[1] if len(mc) >= 2 else mc[0] if mc else 0
    elif token == "COLOR_UNIQUE":
        uniques = [c for c, n in nonzero.items() if n == 1]
        return uniques[0] if uniques else min(nonzero, key=nonzero.get)
    elif token == "COLOR_FG_1":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[0] if mc else 0
    elif token == "COLOR_FG_2":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[1] if len(mc) >= 2 else mc[0] if mc else 0
    return 0


def detect_rule(train_pairs):
    """Check if this learned engine applies to the given training pairs."""
    for inp, out in train_pairs:
        pred = apply_rule(inp, {})
        if pred.shape != out.shape or not np.array_equal(pred, out):
            return None
    return {
        "type": "learned_5582e5ca",
        "description": "Evolved for 5582e5ca: SEQ(FOR_EACH(FOR_EACH(('CROP_TO_COLOR', 'COLOR_UNIQUE'))) -> SEQ(MASK(COLOR_FG_1) -> RECOLOR(COLOR_SECOND,ORIG_COLOR_BG) -> SWAP(COLOR_MAX,COLOR_FG_2)) -> SWAP(COLOR_SECOND,COLOR_FG_2))",
        "target_color": None,
        "displacement": (0, 0),
        "color_swap": None,
        "worst_error": 0.0,
    }


def apply_rule(grid, rule=None):
    """Apply the learned transformation."""
    _orig_grid = grid.copy()
    state = grid.copy()
    def _sub_transform(state):
        _orig_grid = state.copy()
        def _sub_transform(state):
            _orig_grid = state.copy()
        _cv = _resolve_color("COLOR_UNIQUE", _orig_grid)
        nz = np.argwhere(state == _cv)
        if len(nz) > 0:
            r0, c0 = nz.min(axis=0)
            r1, c1 = nz.max(axis=0)
            state = state[r0:r1+1, c0:c1+1].copy()
            return state
        state = _for_each_object(state, _sub_transform)
        return state
    state = _for_each_object(state, _sub_transform)
    state = np.where(state == _resolve_color("COLOR_FG_1", _orig_grid), _resolve_color("COLOR_FG_1", _orig_grid), 0)
    state[state == _resolve_color("COLOR_SECOND", _orig_grid)] = _resolve_color("COLOR_BG", _orig_grid)
    _c1, _c2 = _resolve_color("COLOR_MAX", _orig_grid), _resolve_color("COLOR_FG_2", _orig_grid)
    m1, m2 = state == _c1, state == _c2
    state[m1] = _c2
    state[m2] = _c1
    _c1, _c2 = _resolve_color("COLOR_SECOND", _orig_grid), _resolve_color("COLOR_FG_2", _orig_grid)
    m1, m2 = state == _c1, state == _c2
    state[m1] = _c2
    state[m2] = _c1

    return state


def _gravity(grid, direction):
    """Drop non-zero pixels in a direction."""
    result = np.zeros_like(grid)
    h, w = grid.shape
    if direction == "down":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[h - len(col) + i, c] = v
    elif direction == "up":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[i, c] = v
    elif direction == "right":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, w - len(row) + i] = v
    elif direction == "left":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, i] = v
    return result


def _for_each_object(grid, transform_fn):
    """Apply transform to each connected component."""
    if scipy_label is None:
        return grid
    mask = grid > 0
    if not np.any(mask):
        return grid
    labeled, n = scipy_label(mask)
    if n == 0 or n > 30:
        return grid
    out = np.zeros_like(grid)
    for i in range(1, n + 1):
        obj_mask = (labeled == i)
        isolated = np.where(obj_mask, grid, 0)
        processed = transform_fn(isolated)
        if processed.shape == out.shape:
            pm = processed != 0
            out[pm] = processed[pm]
    return out
