"""
Auto-generated learned engine: learned_445eab21_1775414532
Task: 445eab21
Description: Evolved for 445eab21: SEQ(OVERLAY(SEQ(OVERLAY(OVERLAY(OVERLAY(EXTRACT_QUADRANT_TL, EXTRACT_QUADRANT_BR), EXTRACT_QUADRANT_BL), OVERLAY(EXTRACT_QUADRANT_TR, SORT_COLS)) -> IF_COLOR(COLOR_UNIQUE, EXTRACT_QUADRANT_TL, OVERLAY(IF_COLOR(COLOR_SECOND, FILL_BG(COLOR_MAX), SEQ(DELETE_ROWS_ZERO -> SWAP(COLOR_MIN,COLOR_MAX) -> DELETE_COLS_ZERO)), DELETE_ROWS_ZERO)) -> FILL_BG(COLOR_FG_2)), RECOLOR(COLOR_FG_1,ORIG_COLOR_MIN)) -> RECOLOR_ALL_TO_MAX)
AST: ('SEQ', ('OVERLAY', ('SEQ', ('OVERLAY', ('OVERLAY', ('OVERLAY', 'EXTRACT_QUADRANT_TL', 'EXTRACT_QUADRANT_BR'), 'EXTRACT_QUADRANT_BL'), ('OVERLAY', 'EXTRACT_QUADRANT_TR', 'SORT_COLS')), ('IF_COLOR', 'COLOR_UNIQUE', 'EXTRACT_QUADRANT_TL', ('OVERLAY', ('IF_COLOR', 'COLOR_SECOND', ('FILL_BG', 'COLOR_MAX'), ('SEQ', 'DELETE_ROWS_ZERO', ('SWAP', 'COLOR_MIN', 'COLOR_MAX'), 'DELETE_COLS_ZERO')), 'DELETE_ROWS_ZERO')), ('FILL_BG', 'COLOR_FG_2')), ('RECOLOR', 'COLOR_FG_1', 'ORIG_COLOR_MIN')), 'RECOLOR_ALL_TO_MAX')

Generated by KOS Dream Mode myelination.
DO NOT EDIT -- this file is auto-generated.
"""

import numpy as np
from collections import Counter

try:
    from scipy.ndimage import label as scipy_label
except ImportError:
    scipy_label = None


def _resolve_color(token, grid):
    """Resolve a relational color token to an integer using the grid."""
    if isinstance(token, (int, float, np.integer)):
        return int(token)
    if not isinstance(token, str) or not token.startswith("COLOR_"):
        return token
    flat = grid.flatten()
    freq = Counter(int(v) for v in flat)
    nonzero = {c: n for c, n in freq.items() if c != 0}
    if not nonzero:
        return 0
    if token == "COLOR_MAX":
        return max(nonzero, key=nonzero.get)
    elif token == "COLOR_MIN":
        return min(nonzero, key=nonzero.get)
    elif token == "COLOR_BG":
        return max(freq, key=freq.get) if freq else 0
    elif token == "COLOR_SECOND":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[1] if len(mc) >= 2 else mc[0] if mc else 0
    elif token == "COLOR_UNIQUE":
        uniques = [c for c, n in nonzero.items() if n == 1]
        return uniques[0] if uniques else min(nonzero, key=nonzero.get)
    elif token == "COLOR_FG_1":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[0] if mc else 0
    elif token == "COLOR_FG_2":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[1] if len(mc) >= 2 else mc[0] if mc else 0
    return 0


def detect_rule(train_pairs):
    """Check if this learned engine applies to the given training pairs."""
    for inp, out in train_pairs:
        pred = apply_rule(inp, {})
        if pred.shape != out.shape or not np.array_equal(pred, out):
            return None
    return {
        "type": "learned_445eab21",
        "description": "Evolved for 445eab21: SEQ(OVERLAY(SEQ(OVERLAY(OVERLAY(OVERLAY(EXTRACT_QUADRANT_TL, EXTRACT_QUADRANT_BR), EXTRACT_QUADRANT_BL), OVERLAY(EXTRACT_QUADRANT_TR, SORT_COLS)) -> IF_COLOR(COLOR_UNIQUE, EXTRACT_QUADRANT_TL, OVERLAY(IF_COLOR(COLOR_SECOND, FILL_BG(COLOR_MAX), SEQ(DELETE_ROWS_ZERO -> SWAP(COLOR_MIN,COLOR_MAX) -> DELETE_COLS_ZERO)), DELETE_ROWS_ZERO)) -> FILL_BG(COLOR_FG_2)), RECOLOR(COLOR_FG_1,ORIG_COLOR_MIN)) -> RECOLOR_ALL_TO_MAX)",
        "target_color": None,
        "displacement": (0, 0),
        "color_swap": None,
        "worst_error": 0.0,
    }


def apply_rule(grid, rule=None):
    """Apply the learned transformation."""
    _orig_grid = grid.copy()
    state = grid.copy()
    state_a = state.copy()
    state_a = state.copy()
    state_a = state.copy()
    state_a = state.copy()
    h, w = state.shape
    state = state[:h//2, :w//2].copy()
    result_a = state.copy()
    state = state_a.copy()
    h, w = state.shape
    state = state[h//2:, w//2:].copy()
    result_b = state.copy()
    state = result_a.copy()
    mask = result_b != 0
    state[mask] = result_b[mask]
    result_a = state.copy()
    state = state_a.copy()
    h, w = state.shape
    state = state[h//2:, :w//2].copy()
    result_b = state.copy()
    state = result_a.copy()
    mask = result_b != 0
    state[mask] = result_b[mask]
    result_a = state.copy()
    state = state_a.copy()
    state_a = state.copy()
    h, w = state.shape
    state = state[:h//2, w//2:].copy()
    result_a = state.copy()
    state = state_a.copy()
    state = np.sort(state, axis=0)
    result_b = state.copy()
    state = result_a.copy()
    mask = result_b != 0
    state[mask] = result_b[mask]
    result_b = state.copy()
    state = result_a.copy()
    mask = result_b != 0
    state[mask] = result_b[mask]
    if _resolve_color("COLOR_UNIQUE", _orig_grid) in state:
        h, w = state.shape
        state = state[:h//2, :w//2].copy()
    else:
        state_a = state.copy()
        if _resolve_color("COLOR_SECOND", _orig_grid) in state:
            state[state == 0] = _resolve_color("COLOR_MAX", _orig_grid)
        else:
            mask = np.any(state != 0, axis=1)
            if mask.any(): state = state[mask]
            _c1, _c2 = _resolve_color("COLOR_MIN", _orig_grid), _resolve_color("COLOR_MAX", _orig_grid)
            m1, m2 = state == _c1, state == _c2
            state[m1] = _c2
            state[m2] = _c1
            mask = np.any(state != 0, axis=0)
            if mask.any(): state = state[:, mask]
        result_a = state.copy()
        state = state_a.copy()
        mask = np.any(state != 0, axis=1)
        if mask.any(): state = state[mask]
        result_b = state.copy()
        state = result_a.copy()
        mask = result_b != 0
        state[mask] = result_b[mask]
    state[state == 0] = _resolve_color("COLOR_FG_2", _orig_grid)
    result_a = state.copy()
    state = state_a.copy()
    state[state == _resolve_color("COLOR_FG_1", _orig_grid)] = _resolve_color("COLOR_MIN", _orig_grid)
    result_b = state.copy()
    state = result_a.copy()
    mask = result_b != 0
    state[mask] = result_b[mask]
    _cmax = _resolve_color('COLOR_MAX', _orig_grid)
    state[state != 0] = _cmax

    return state


def _gravity(grid, direction):
    """Drop non-zero pixels in a direction."""
    result = np.zeros_like(grid)
    h, w = grid.shape
    if direction == "down":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[h - len(col) + i, c] = v
    elif direction == "up":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[i, c] = v
    elif direction == "right":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, w - len(row) + i] = v
    elif direction == "left":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, i] = v
    return result


def _for_each_object(grid, transform_fn):
    """Apply transform to each connected component."""
    if scipy_label is None:
        return grid
    mask = grid > 0
    if not np.any(mask):
        return grid
    labeled, n = scipy_label(mask)
    if n == 0 or n > 30:
        return grid
    out = np.zeros_like(grid)
    for i in range(1, n + 1):
        obj_mask = (labeled == i)
        isolated = np.where(obj_mask, grid, 0)
        processed = transform_fn(isolated)
        if processed.shape == out.shape:
            pm = processed != 0
            out[pm] = processed[pm]
    return out
