"""
Auto-generated learned engine: learned_9565186b_1775400898
Task: 9565186b
Description: Evolved for 9565186b: FOR_EACH(SEQ(MASK(ORIG_COLOR_MAX) -> KEEP_MOST_FREQUENT))
AST: ('FOR_EACH_OBJECT', ('SEQ', ('MASK', 'ORIG_COLOR_MAX'), 'KEEP_MOST_FREQUENT'))

Generated by KOS Dream Mode myelination.
DO NOT EDIT -- this file is auto-generated.
"""

import numpy as np
from collections import Counter

try:
    from scipy.ndimage import label as scipy_label
except ImportError:
    scipy_label = None


def _resolve_color(token, grid):
    """Resolve a relational color token to an integer using the grid."""
    if isinstance(token, (int, float, np.integer)):
        return int(token)
    if not isinstance(token, str) or not token.startswith("COLOR_"):
        return token
    flat = grid.flatten()
    freq = Counter(int(v) for v in flat)
    nonzero = {c: n for c, n in freq.items() if c != 0}
    if not nonzero:
        return 0
    if token == "COLOR_MAX":
        return max(nonzero, key=nonzero.get)
    elif token == "COLOR_MIN":
        return min(nonzero, key=nonzero.get)
    elif token == "COLOR_BG":
        return max(freq, key=freq.get) if freq else 0
    elif token == "COLOR_SECOND":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[1] if len(mc) >= 2 else mc[0] if mc else 0
    elif token == "COLOR_UNIQUE":
        uniques = [c for c, n in nonzero.items() if n == 1]
        return uniques[0] if uniques else min(nonzero, key=nonzero.get)
    elif token == "COLOR_FG_1":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[0] if mc else 0
    elif token == "COLOR_FG_2":
        mc = sorted(nonzero, key=nonzero.get, reverse=True)
        return mc[1] if len(mc) >= 2 else mc[0] if mc else 0
    return 0


def detect_rule(train_pairs):
    """Check if this learned engine applies to the given training pairs."""
    for inp, out in train_pairs:
        pred = apply_rule(inp, {})
        if pred.shape != out.shape or not np.array_equal(pred, out):
            return None
    return {
        "type": "learned_9565186b",
        "description": "Evolved for 9565186b: FOR_EACH(SEQ(MASK(ORIG_COLOR_MAX) -> KEEP_MOST_FREQUENT))",
        "target_color": None,
        "displacement": (0, 0),
        "color_swap": None,
        "worst_error": 0.0,
    }


def apply_rule(grid, rule=None):
    """Apply the learned transformation."""
    _orig_grid = grid.copy()
    state = grid.copy()
    def _sub_transform(state):
        _orig_grid = state.copy()
        state = np.where(state == _resolve_color("COLOR_MAX", _orig_grid), _resolve_color("COLOR_MAX", _orig_grid), 0)
        _freq = {}
        for v in state.flat:
            if int(v) != 0: _freq[int(v)] = _freq.get(int(v), 0) + 1
        if _freq:
            _keep = max(_freq, key=_freq.get)
            state = np.where((state == _keep) | (state == 0), state, 0)
        return state
    state = _for_each_object(state, _sub_transform)

    return state


def _gravity(grid, direction):
    """Drop non-zero pixels in a direction."""
    result = np.zeros_like(grid)
    h, w = grid.shape
    if direction == "down":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[h - len(col) + i, c] = v
    elif direction == "up":
        for c in range(w):
            col = [grid[r, c] for r in range(h) if grid[r, c] != 0]
            for i, v in enumerate(col):
                result[i, c] = v
    elif direction == "right":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, w - len(row) + i] = v
    elif direction == "left":
        for r in range(h):
            row = [grid[r, c] for c in range(w) if grid[r, c] != 0]
            for i, v in enumerate(row):
                result[r, i] = v
    return result


def _for_each_object(grid, transform_fn):
    """Apply transform to each connected component."""
    if scipy_label is None:
        return grid
    mask = grid > 0
    if not np.any(mask):
        return grid
    labeled, n = scipy_label(mask)
    if n == 0 or n > 30:
        return grid
    out = np.zeros_like(grid)
    for i in range(1, n + 1):
        obj_mask = (labeled == i)
        isolated = np.where(obj_mask, grid, 0)
        processed = transform_fn(isolated)
        if processed.shape == out.shape:
            pm = processed != 0
            out[pm] = processed[pm]
    return out
